[package]
name = "backpack-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "backpack_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
dirs = "6"
tauri = { version = "2", features = [] }
backpack-core = { path = "../crates/backpack-core" }

[features]
custom-protocol = ["tauri/custom-protocol"]
