import LibraryInstall from "./LibraryInstall";
import { useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import type { LibraryComparison, LibraryEntry, LibraryPreview, Resource, ScanRequest } from "./types";
const preferenceKey="backpack.library-folder.v1";
function savedPath() {try{return localStorage.getItem(preferenceKey)??"";}catch{return "";}}
const labels={equal:"동일",changed:"내용 다름",libraryOnly:"라이브러리에만 있음",localOnly:"로컬에만 있음"};
interface Props {resources:Resource[];request:ScanRequest;native:boolean;disabled:boolean;selectedId:string;scannedAt:number;onSelection:(id:string)=>void;onBusy:(busy:boolean)=>void;onChanged:()=>void}
export default function LibraryPanel(props:Props) {
  const [path,setPath]=useState(savedPath);const [connected,setConnected]=useState("");const [items,setItems]=useState<LibraryEntry[]>([]);
  const [installBusy,setInstallBusy]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [preview,setPreview]=useState<LibraryPreview|null>(null);const [reviewed,setReviewed]=useState(false);
  const [compareIds,setCompareIds]=useState<Record<string,string>>({});const [comparisons,setComparisons]=useState<Record<string,LibraryComparison>>({});
  const version=useRef(0);
  const resources=props.resources.filter(r=>r.origin!=="bundled"&&["skill","rule","tool","hook","plugin"].includes(r.kind));
  const locked=installBusy||busy||props.disabled||!props.native;
  async function work(run:()=>Promise<void>) {setBusy(true);props.onBusy(true);setError("");setMessage("");try{await run();}catch(e){setError(typeof e==="string"?e:"라이브러리 작업을 완료하지 못했습니다.");}finally{setBusy(false);props.onBusy(false);}}
  useEffect(()=>{const current=++version.current;const saved=savedPath();if(props.native&&saved){void invoke<LibraryEntry[]>("list_library",{path:saved}).then(next=>{if(version.current===current){setConnected(saved);setItems(next);}}).catch(()=>{if(version.current===current)setError("저장된 라이브러리 폴더를 확인하지 못했습니다. 경로를 확인하고 다시 연결하세요.");});}return()=>{version.current++;};},[props.native]);
  useEffect(()=>{setPreview(null);setReviewed(false);setComparisons({});},[props.selectedId,props.request,props.scannedAt]);
  async function connect() {version.current++;setPreview(null);setReviewed(false);setComparisons({});await work(async()=>{const folder=path.trim();const next=await invoke<LibraryEntry[]>("connect_library",{path:folder});setConnected(folder);setItems(next);try{localStorage.setItem(preferenceKey,folder);}catch{setMessage("연결됐지만 폴더 경로를 이 PC에 저장하지 못했습니다.");}});}
  async function refresh() {await work(async()=>setItems(await invoke<LibraryEntry[]>("list_library",{path:connected})));}
  async function review() {setPreview(null);setReviewed(false);await work(async()=>setPreview(await invoke<LibraryPreview>("preview_library_import",{path:connected,request:props.request,resourceId:props.selectedId})));}
  async function save() {if(!preview||!reviewed)return;const token=preview.token;setPreview(null);await work(async()=>{await invoke("import_library_item",{token,reviewed});setItems(await invoke<LibraryEntry[]>("list_library",{path:connected}));setMessage("새 라이브러리 항목으로 저장했습니다. 원본 파일은 변경하지 않았습니다.");});}
  async function compare(itemId:string) {const resourceId=compareIds[itemId];if(!resourceId)return;await work(async()=>{const result=await invoke<LibraryComparison>("compare_library_item",{path:connected,itemId,resourceId,request:props.request});setComparisons(previous=>({...previous,[itemId]:result}));});}
  function disconnect() {version.current++;setConnected("");setItems([]);setPreview(null);setComparisons({});try{localStorage.removeItem(preferenceKey);}catch{setError("저장된 연결 경로를 지우지 못했습니다.");}}
  return <section className="library-panel" aria-label="공유 라이브러리"><h2>공유 라이브러리</h2><p className="inspection-hint">기존 로컬 폴더를 연결합니다. 연결 시 폴더 안에 .backpack-library를 만들고 파일 묶음을 저장합니다. 저장한 항목을 지원되는 에이전트 경로에 설치할 수 있습니다. 클라우드 업로드는 아직 지원하지 않습니다.</p>
    <label className="field">라이브러리 폴더 (절대 경로)<input value={path} disabled={locked} onChange={e=>setPath(e.target.value)} placeholder="예: C:\Users\me\Backpack-library"/></label>
    <div className="library-actions"><button className="secondary" disabled={locked||!path.trim()} onClick={()=>void connect()}>폴더 연결</button>{connected&&<><button className="secondary" disabled={locked} onClick={()=>void refresh()}>목록 새로고침</button><button className="text-button" disabled={locked} onClick={disconnect}>연결 해제</button></>}</div>
    {connected&&<><code className="library-location">{connected}</code><h3>로컬 항목 가져오기</h3><label className="field">가져올 리소스<select disabled={locked} value={props.selectedId} onChange={e=>props.onSelection(e.target.value)}><option value="">리소스 선택</option>{resources.map(r=><option key={r.id} value={r.id}>{r.name} · {r.agentId} · {r.scope} · {r.kind}</option>)}</select></label><button className="secondary" disabled={locked||!props.selectedId} onClick={()=>void review()}>가져오기 미리보기</button>
    {preview&&<div className="change-preview"><h4>{preview.change.name} · {preview.change.files.length}개 파일 · {preview.change.totalBytes.toLocaleString()} bytes</h4><p>{preview.change.note}</p><ul className="library-files">{preview.change.files.map(f=><li key={f.path}><code>{f.path}</code><small>{f.size.toLocaleString()} bytes</small></li>)}</ul>{preview.change.skipped.length>0&&<details><summary>제외 항목 {preview.change.skipped.length}개</summary><ul>{preview.change.skipped.map(p=><li key={p}><code>{p}</code></li>)}</ul></details>}<label className="inspection-option"><input type="checkbox" checked={reviewed} disabled={locked} onChange={e=>setReviewed(e.target.checked)}/>원본 파일을 검토했고 공유하면 안 되는 비밀 값이 없음을 확인했습니다.</label><button className="primary" disabled={locked||!reviewed} onClick={()=>void save()}>라이브러리에 저장</button><button className="secondary" disabled={locked} onClick={()=>setPreview(null)}>취소</button></div>}
    <h3>저장한 항목 · {items.length}개</h3>{!items.length&&<p className="inspection-hint">저장한 파일 묶음이 없습니다.</p>}{items.map(item=><article className="library-item" key={item.id}><strong>{item.name}</strong><small>{item.agentId} · {item.kind} · {item.files.length}개 파일 · {new Date(item.createdAt*1000).toLocaleString("ko-KR")}</small><label className="field">비교할 로컬 리소스<select disabled={locked} value={compareIds[item.id]??""} onChange={e=>{setCompareIds(previous=>({...previous,[item.id]:e.target.value}));setComparisons(previous=>{const next={...previous};delete next[item.id];return next;});}}><option value="">같은 종류의 리소스 선택</option>{resources.filter(r=>r.kind===item.kind).map(r=><option key={r.id} value={r.id}>{r.name} · {r.agentId} · {r.scope}</option>)}</select></label><button className="secondary" disabled={locked||!compareIds[item.id]} onClick={()=>void compare(item.id)}>파일 비교</button>{comparisons[item.id]&&<div className="library-comparison" role="status"><strong>{comparisons[item.id].identical?"모든 파일이 같습니다":"파일 차이가 있습니다"}</strong><ul>{comparisons[item.id].files.map(f=><li key={f.path}><code>{f.path}</code> · {labels[f.status]}</li>)}</ul></div>}<LibraryInstall path={connected} itemId={item.id} request={props.request} scannedAt={props.scannedAt} disabled={locked} onBusy={value=>{setInstallBusy(value);props.onBusy(value);if(value)setPreview(null);}} onChanged={props.onChanged}/></article>)}</>}
    {error&&<p className="inspection-error" role="alert">{error}</p>}{message&&<p className="inspection-hint" role="status">{message}</p>}
  </section>;
}
